//
//  Catalog.swift
//  CaipirinIA
//
//  Created by Clément Deust on 31/08/2024.
//

import Foundation

let ingredientMapping: [String: String] = [
    // Base Spirits
    "vodka": "Vodka",
    "vodka bottle": "Vodka",
    "whisky": "Whiskey",
    "whiskey": "Whiskey",
    "scotch whisky": "Whiskey",
    "scotch": "Whiskey",
    "bourbon": "Bourbon",
    "gin": "Gin",
    "gin bottle": "Gin",
    "rum": "Rum",
    "white rum": "Rum",
    "dark rum": "Rum",
    "tequila": "Tequila",
    "mezcal": "Tequila",
    "brandy": "Brandy",
    "cognac": "Brandy",
    "absinthe": "Absinthe",
    "schnapps": "Schnapps",
    "champagne": "Champagne",
    "beer": "Beer",
    "cider": "Cider",
    "wine": "Wine",
    "red wine": "Wine",
    "white wine": "Wine",

    // Modifiers
    "vermouth": "Vermouth",
    "dry vermouth": "Vermouth",
    "sweet vermouth": "Vermouth",
    "triple sec": "Triple Sec",
    "cointreau": "Triple Sec",
    "orange liqueur": "Triple Sec",
    "blue curacao": "Curacao",
    "curacao": "Curacao",
    "amaretto": "Amaretto",
    "campari": "Campari",
    "aperol": "Aperol",
    "maraschino liqueur": "Maraschino Liqueur",
    "baileys": "Irish Cream Liqueur",
    "bailey's irish cream": "Irish Cream Liqueur",
    "kahlua": "Coffee Liqueur",
    "coffee liqueur": "Coffee Liqueur",
    "grand marnier": "Grand Marnier",
    "cherry liqueur": "Cherry Liqueur",
    "peach schnapps": "Peach Schnapps",

    // Sweeteners
    "simple syrup": "Simple Syrup",
    "syrup": "Simple Syrup",
    "honey syrup": "Honey Syrup",
    "honey": "Honey Syrup",
    "maple syrup": "Maple Syrup",
    "agave syrup": "Agave Syrup",
    "grenadine": "Grenadine",
    "orgeat syrup": "Orgeat Syrup",
    "falernum": "Falernum",

    // Sours
    "lemon juice": "Lemon Juice",
    "lemon": "Lemon Juice",
    "lime juice": "Lime Juice",
    "lime": "Lime Juice",
    "orange juice": "Orange Juice",
    "grapefruit juice": "Grapefruit Juice",
    "pineapple juice": "Pineapple Juice",
    "cranberry juice": "Cranberry Juice",
    "pomegranate juice": "Pomegranate Juice",

    // Bitters
    "angostura bitters": "Angostura Bitters",
    "orange bitters": "Orange Bitters",
    "peychaud's bitters": "Peychaud's Bitters",
    "chocolate bitters": "Chocolate Bitters",
    "coffee bitters": "Coffee Bitters",

    // Mixers (Sodas)
    "club soda": "Soda Water",
    "soda water": "Soda Water",
    "tonic": "Tonic Water",
    "tonic water": "Tonic Water",
    "ginger beer": "Ginger Beer",
    "ginger ale": "Ginger Ale",
    "cola": "Cola",
    "coca-cola": "Cola",
    "pepsi": "Cola",
    "sprite": "Lemon-Lime Soda",
    "7up": "Lemon-Lime Soda",
    "mountain dew": "Citrus Soda",
    "root beer": "Root Beer",
    "club soda": "Soda Water",
    "cream soda": "Cream Soda",

    // Dairy and Non-Dairy
    "milk": "Milk",
    "cream": "Cream",
    "half and half": "Cream",
    "coconut milk": "Coconut Milk",
    "almond milk": "Almond Milk",
    "evaporated milk": "Evaporated Milk",

    // Garnishes
    "mint": "Mint",
    "lime wedge": "Lime Wedge",
    "lemon twist": "Lemon Twist",
    "orange slice": "Orange Slice",
    "cherry": "Cherry",
    "maraschino cherry": "Cherry",
    "olive": "Olive",
    "cucumber slice": "Cucumber Slice",
    "rosemary sprig": "Rosemary Sprig",
    "cinnamon stick": "Cinnamon Stick",
    "sugar rim": "Sugar Rim",
    "salt rim": "Salt Rim",
    "chocolate shavings": "Chocolate Shavings",

    // Fruits and Vegetables
    "strawberry": "Strawberry",
    "banana": "Banana",
    "blueberries": "Blueberry",
    "blackberries": "Blackberry",
    "raspberry": "Raspberry",
    "cucumber": "Cucumber",
    "pineapple": "Pineapple",
    "peach": "Peach",
    "watermelon": "Watermelon",
    "orange": "Orange",
    "lemon": "Lemon",
    "lime": "Lime",

    // Miscellaneous
    "egg white": "Egg White",
    "egg yolk": "Egg Yolk",
    "sugar": "Sugar",
    "powdered sugar": "Powdered Sugar",
    "vanilla extract": "Vanilla Extract",
    "nutmeg": "Nutmeg",
    "cinnamon": "Cinnamon",
    "ice": "Ice"
]

let ingredientsCatalog: [Ingredient] = [
    // Base Spirits
    Ingredient(name: "Vodka", type: .baseSpirit),
    Ingredient(name: "Gin", type: .baseSpirit),
    Ingredient(name: "Rum", type: .baseSpirit),
    Ingredient(name: "Tequila", type: .baseSpirit),
    Ingredient(name: "Whiskey", type: .baseSpirit),
    Ingredient(name: "Bourbon", type: .baseSpirit),
    Ingredient(name: "Scotch", type: .baseSpirit),
    Ingredient(name: "Brandy", type: .baseSpirit),
    Ingredient(name: "Cognac", type: .baseSpirit),
    Ingredient(name: "Mezcal", type: .baseSpirit),
    Ingredient(name: "Absinthe", type: .baseSpirit),
    Ingredient(name: "Pisco", type: .baseSpirit),
    Ingredient(name: "Calvados", type: .baseSpirit),
    Ingredient(name: "Sake", type: .baseSpirit),

    // Modifiers
    Ingredient(name: "Vermouth", type: .modifier),
    Ingredient(name: "Triple Sec", type: .modifier),
    Ingredient(name: "Cointreau", type: .modifier),
    Ingredient(name: "Amaretto", type: .modifier),
    Ingredient(name: "Campari", type: .modifier),
    Ingredient(name: "Aperol", type: .modifier),
    Ingredient(name: "Maraschino Liqueur", type: .modifier),
    Ingredient(name: "Kahlua", type: .modifier),
    Ingredient(name: "Baileys", type: .modifier),
    Ingredient(name: "Grand Marnier", type: .modifier),
    Ingredient(name: "Blue Curacao", type: .modifier),
    Ingredient(name: "Dry Vermouth", type: .modifier),
    Ingredient(name: "Sweet Vermouth", type: .modifier),
    Ingredient(name: "St. Germain", type: .modifier),
    Ingredient(name: "Lillet Blanc", type: .modifier),
    Ingredient(name: "Creme de Cassis", type: .modifier),
    Ingredient(name: "Frangelico", type: .modifier),
    Ingredient(name: "Chambord", type: .modifier),

    // Sweeteners
    Ingredient(name: "Simple Syrup", type: .sweetener),
    Ingredient(name: "Honey Syrup", type: .sweetener),
    Ingredient(name: "Maple Syrup", type: .sweetener),
    Ingredient(name: "Agave Syrup", type: .sweetener),
    Ingredient(name: "Grenadine", type: .sweetener),
    Ingredient(name: "Orgeat Syrup", type: .sweetener),
    Ingredient(name: "Falernum", type: .sweetener),
    Ingredient(name: "Elderflower Syrup", type: .sweetener),
    Ingredient(name: "Vanilla Syrup", type: .sweetener),
    Ingredient(name: "Ginger Syrup", type: .sweetener),

    // Sours
    Ingredient(name: "Lemon Juice", type: .sour),
    Ingredient(name: "Lime Juice", type: .sour),
    Ingredient(name: "Orange Juice", type: .sour),
    Ingredient(name: "Grapefruit Juice", type: .sour),
    Ingredient(name: "Pineapple Juice", type: .sour),
    Ingredient(name: "Cranberry Juice", type: .sour),
    Ingredient(name: "Pomegranate Juice", type: .sour),
    Ingredient(name: "Tamarind Juice", type: .sour),
    Ingredient(name: "Passion Fruit Juice", type: .sour),
    Ingredient(name: "Yuzu Juice", type: .sour),

    // Bitters
    Ingredient(name: "Angostura Bitters", type: .bitter),
    Ingredient(name: "Orange Bitters", type: .bitter),
    Ingredient(name: "Peychaud's Bitters", type: .bitter),
    Ingredient(name: "Chocolate Bitters", type: .bitter),
    Ingredient(name: "Coffee Bitters", type: .bitter),
    Ingredient(name: "Lavender Bitters", type: .bitter),
    Ingredient(name: "Grapefruit Bitters", type: .bitter),
    Ingredient(name: "Celery Bitters", type: .bitter),
    Ingredient(name: "Peach Bitters", type: .bitter),

    // Garnishes
    Ingredient(name: "Mint", type: .garnish),
    Ingredient(name: "Lime Wedge", type: .garnish),
    Ingredient(name: "Lemon Twist", type: .garnish),
    Ingredient(name: "Orange Slice", type: .garnish),
    Ingredient(name: "Cherry", type: .garnish),
    Ingredient(name: "Olive", type: .garnish),
    Ingredient(name: "Cucumber Slice", type: .garnish),
    Ingredient(name: "Rosemary Sprig", type: .garnish),
    Ingredient(name: "Cinnamon Stick", type: .garnish),
    Ingredient(name: "Sugar Rim", type: .garnish),
    Ingredient(name: "Salt Rim", type: .garnish),
    Ingredient(name: "Chocolate Shavings", type: .garnish),
    Ingredient(name: "Pineapple Leaf", type: .garnish),
    Ingredient(name: "Edible Flower", type: .garnish),
    Ingredient(name: "Star Anise", type: .garnish),
    Ingredient(name: "Orange Peel", type: .garnish)
]
